# Generated by Django 5.0.7 on 2024-07-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ManyToManyField(related_name='services', to='category.category'),
        ),
    ]
