# Generated by Django 5.0.7 on 2024-07-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='category',
            new_name='categories',
        ),
    ]
